/* Datos de la seccion "Comparativa" (mapa competitivo). Modulo de datos PURO
   (sin React, sin fetch) para poder probarse con node --test y para que la
   UI (src/features/compare/ComparePage.jsx) solo consuma esta estructura.

   Reglas de esta tabla (pedidas explicitamente en la auditoria que la
   origino):
   - Nunca inventar: un valor solo es true/false si una fuente publica lo
     confirma. Todo lo demas es NOT_CONFIRMED.
   - ZOEMEC no se marca "unico en el mundo" en nada: sus casillas reflejan
     funcionalidad real y probada en este repositorio (ver los *.test.js de
     src/domain para cada motor), nunca una afirmacion de marketing.
   - Un par de herramientas mencionadas en la auditoria original
     ("EstimateNext" como producto independiente, "ConstruBase" como
     competidor separado de Neodata) no pudieron confirmarse como productos
     comerciales distintos e identificables al momento de esta revision
     (sep-2026): ConstruBase aparece en fuentes publicas como el NOMBRE de la
     base de datos de Neodata, no como una empresa/producto aparte; no se
     encontro una pagina oficial verificable de un producto llamado
     "EstimateNext". Se excluyen de la tabla en vez de inventar datos sobre
     ellos -- ver metodologia en la propia pagina. */

export const VAL = Object.freeze({
  YES: 'yes',
  NO: 'no',
  PARTIAL: 'partial',
  NOT_CONFIRMED: 'not_confirmed',
});

export const CATEGORIES = Object.freeze({
  TAKEOFF: 'takeoff',
  ESTIMATING: 'estimating',
  AI: 'ai',
  APU: 'apu',
  ENTERPRISE: 'enterprise',
});

/* Cada feature tiene una key (usada como columna) y una etiqueta i18n
   (compare.feature.<key>) resuelta en translations.js. */
export const FEATURE_LIST = [
  'apu',
  'apuAI',
  'takeoff2d',
  'takeoff3d',
  'digitalTwin',
  'confidenceEngine',
  'bidRisk',
  'scenarioEngine',
  'auditEngine',
  'technicalMemory',
  'pdfExport',
  'excelExport',
  'bimIntegration',
  'collaboration',
  'latamFocus',
];

export const COMPETITORS = [
  {
    id: 'zoemec',
    name: 'ZOEMEC',
    categories: [CATEGORIES.APU, CATEGORIES.AI, CATEGORIES.ESTIMATING],
    region: 'México / LatAm',
    url: 'https://zoemecia.com',
    pricingNote: 'Plan Gratis (1 APU) + planes de pago por suscripción.',
    pricingConfirmed: true,
    features: {
      apu: VAL.YES,
      apuAI: VAL.YES,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.PARTIAL,
      digitalTwin: VAL.YES,
      confidenceEngine: VAL.YES,
      bidRisk: VAL.YES,
      scenarioEngine: VAL.YES,
      auditEngine: VAL.YES,
      technicalMemory: VAL.YES,
      pdfExport: VAL.YES,
      excelExport: VAL.YES,
      bimIntegration: VAL.NOT_CONFIRMED,
      collaboration: VAL.NOT_CONFIRMED,
      latamFocus: VAL.YES,
    },
  },
  {
    id: 'stack',
    name: 'STACK',
    categories: [CATEGORIES.TAKEOFF, CATEGORIES.ESTIMATING, CATEGORIES.AI],
    region: 'EE. UU. / Internacional',
    url: 'https://www.stackct.com',
    pricingNote: 'Desde ~$599/año (Build & Operate); Takeoff & Estimate ~$2,599/año.',
    pricingConfirmed: true,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.NOT_CONFIRMED,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.YES,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NOT_CONFIRMED,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'togal',
    name: 'Togal.AI',
    categories: [CATEGORIES.TAKEOFF, CATEGORIES.AI],
    region: 'EE. UU. / Internacional',
    url: 'https://www.togal.ai',
    pricingNote: 'Desde ~$250-299/usuario/mes (planes por nivel).',
    pricingConfirmed: true,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.NOT_CONFIRMED,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NOT_CONFIRMED,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'kreo',
    name: 'Kreo',
    categories: [CATEGORIES.TAKEOFF, CATEGORIES.AI, CATEGORIES.ESTIMATING],
    region: 'Reino Unido / Internacional',
    url: 'https://www.kreo.net',
    pricingNote: 'Prueba gratis; precio por plan no publicado con detalle.',
    pricingConfirmed: false,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.NOT_CONFIRMED,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.YES,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NOT_CONFIRMED,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'autodesk-takeoff',
    name: 'Autodesk Takeoff (Forma Takeoff)',
    categories: [CATEGORIES.TAKEOFF, CATEGORIES.ENTERPRISE],
    region: 'EE. UU. / Internacional',
    url: 'https://construction.autodesk.com/products/autodesk-takeoff/',
    pricingNote: '~$1,250/usuario/año o ~$155/usuario/mes; también incluido en paquetes ACC.',
    pricingConfirmed: true,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.YES,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.YES,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'procore-estimating',
    name: 'Procore Estimating',
    categories: [CATEGORIES.ESTIMATING, CATEGORIES.ENTERPRISE],
    region: 'EE. UU. / Internacional',
    url: 'https://www.procore.com',
    pricingNote: '~$300-500/usuario/mes; no se vende de forma independiente de Procore.',
    pricingConfirmed: true,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.NOT_CONFIRMED,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NOT_CONFIRMED,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'rib-costx',
    name: 'RIB CostX',
    categories: [CATEGORIES.TAKEOFF, CATEGORIES.ESTIMATING, CATEGORIES.ENTERPRISE],
    region: 'Internacional (Alemania/Australia)',
    url: 'https://www.rib-software.com',
    pricingNote: 'Cotización personalizada (no publicada).',
    pricingConfirmed: false,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.YES,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.YES,
      excelExport: VAL.YES,
      bimIntegration: VAL.YES,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'bluebeam',
    name: 'Bluebeam Revu',
    categories: [CATEGORIES.TAKEOFF],
    region: 'EE. UU. / Internacional',
    url: 'https://www.bluebeam.com',
    pricingNote: 'Licencia por usuario (consultar sitio oficial).',
    pricingConfirmed: false,
    features: {
      apu: VAL.NO,
      apuAI: VAL.NO,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.NO,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.YES,
      bimIntegration: VAL.NOT_CONFIRMED,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'planswift',
    name: 'PlanSwift',
    categories: [CATEGORIES.TAKEOFF, CATEGORIES.ESTIMATING],
    region: 'EE. UU. / Internacional',
    url: 'https://www.planswift.com',
    pricingNote: 'Licencia por usuario (consultar sitio oficial).',
    pricingConfirmed: false,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NO,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.NO,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NO,
      collaboration: VAL.PARTIAL,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'buildxact',
    name: 'Buildxact',
    categories: [CATEGORIES.ESTIMATING],
    region: 'Australia / EE. UU.',
    url: 'https://www.buildxact.com',
    pricingNote: 'Suscripción mensual (consultar sitio oficial).',
    pricingConfirmed: false,
    features: {
      apu: VAL.NOT_CONFIRMED,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.YES,
      takeoff3d: VAL.NO,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NO,
      collaboration: VAL.YES,
      latamFocus: VAL.NO,
    },
  },
  {
    id: 'opus',
    name: 'OPUS (Ecosoft)',
    categories: [CATEGORIES.APU, CATEGORIES.ESTIMATING, CATEGORIES.ENTERPRISE],
    region: 'México',
    url: 'https://opus-planet.mx',
    pricingNote: 'Licencia por módulo (consultar distribuidor autorizado).',
    pricingConfirmed: false,
    features: {
      apu: VAL.YES,
      apuAI: VAL.NOT_CONFIRMED,
      takeoff2d: VAL.NOT_CONFIRMED,
      takeoff3d: VAL.NO,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NO,
      collaboration: VAL.NOT_CONFIRMED,
      latamFocus: VAL.YES,
    },
  },
  {
    id: 'neodata',
    name: 'Neodata (ConstruBase)',
    categories: [CATEGORIES.APU, CATEGORIES.ESTIMATING],
    region: 'México',
    url: 'https://neodata.mx',
    pricingNote: 'Licenciamiento en la nube por usuario (consultar distribuidor autorizado).',
    pricingConfirmed: false,
    features: {
      apu: VAL.YES,
      apuAI: VAL.NO,
      takeoff2d: VAL.NO,
      takeoff3d: VAL.NO,
      digitalTwin: VAL.NOT_CONFIRMED,
      confidenceEngine: VAL.NOT_CONFIRMED,
      bidRisk: VAL.NOT_CONFIRMED,
      scenarioEngine: VAL.NOT_CONFIRMED,
      auditEngine: VAL.NOT_CONFIRMED,
      technicalMemory: VAL.NOT_CONFIRMED,
      pdfExport: VAL.NOT_CONFIRMED,
      excelExport: VAL.NOT_CONFIRMED,
      bimIntegration: VAL.NO,
      collaboration: VAL.NOT_CONFIRMED,
      latamFocus: VAL.YES,
    },
  },
];

/* Diferenciadores reales de ZOEMEC para la seccion "Por que ZOEMEC": cada uno
   apunta a un modulo con pruebas automatizadas en este mismo repositorio
   (ver src/domain/*.test.js), no a una promesa de marketing. */
export const WHY_ZOEMEC = [
  { key: 'combo', evidence: 'src/domain/apuConfidence.js, bidRisk.js, apuScenario.js, apuAuditor.js, apuChallenge.js' },
  { key: 'traceability', evidence: 'src/lib/apuExport.js, apuDossierPdf.js, apuDossierXlsx.js (Dossier APU Auditable)' },
  { key: 'methodology', evidence: 'FSR / RLOPSRM: src/lib/apuCalc.js' },
  { key: 'bilingual', evidence: 'src/i18n/translations.js' },
  { key: 'regional', evidence: 'metodología mexicana (RLOPSRM) con soporte bilingüe ES/EN' },
];
