import test from 'node:test';
import assert from 'node:assert/strict';
import {
  foldDescription, normalizeUnitForGrouping, isAutogeneratedClave, groupKeyFor,
  reconcilePrice, median, assertSingleTenantScope, buildExplosionSnapshot, RECONCILIATION_RULE
} from './explosionEngine.js';

test('foldDescription ignora acentos/mayusculas/espacios dobles', () => {
  assert.equal(foldDescription('Cemento  CPC 30R'), foldDescription('cemento cpc 30r'));
  assert.equal(foldDescription('Válvula Check'), foldDescription('valvula check'));
});

test('normalizeUnitForGrouping trata m2/M2/m² como la misma unidad pero NUNCA une bulto con kg', () => {
  assert.equal(normalizeUnitForGrouping('m2'), normalizeUnitForGrouping('M²'));
  assert.notEqual(normalizeUnitForGrouping('bulto'), normalizeUnitForGrouping('kg'));
});

test('isAutogeneratedClave detecta el placeholder por indice de apuSchema.js', () => {
  assert.equal(isAutogeneratedClave('MAT-001', 'materials'), true);
  assert.equal(isAutogeneratedClave('CEM-CPC30R', 'materials'), false);
  assert.equal(isAutogeneratedClave('', 'materials'), true);
  // kind desconocido (ej. herramientaMenor): nunca se asume confiable por defecto
  assert.equal(isAutogeneratedClave('CUALQUIERA', 'herramientaMenor'), true);
});

test('groupKeyFor separa el mismo nombre cuando la unidad es incompatible (TEST QA 5)', () => {
  const bulto = groupKeyFor({ clave: 'MAT-001', descripcion: 'Cemento CPC 30R', unidad: 'bulto' }, 'materials');
  const kg = groupKeyFor({ clave: 'MAT-001', descripcion: 'Cemento CPC 30R', unidad: 'kg' }, 'materials');
  assert.notEqual(bulto, kg);
});

test('groupKeyFor agrupa la misma clave real con unidad cosmeticamente distinta', () => {
  const a = groupKeyFor({ clave: 'CEM-CPC30R', descripcion: 'Cemento', unidad: 'm2' }, 'materials');
  const b = groupKeyFor({ clave: 'CEM-CPC30R', descripcion: 'Cemento (otra redaccion)', unidad: 'M²' }, 'materials');
  assert.equal(a, b);
});

test('reconcilePrice: precios iguales -> regla UNICO', () => {
  const result = reconcilePrice([{ precioUnitario: 10, confidence: 50 }, { precioUnitario: 10, confidence: 90 }]);
  assert.equal(result.rule, RECONCILIATION_RULE.UNICO);
  assert.equal(result.precioUnitario, 10);
});

test('reconcilePrice: precios distintos -> gana la mayor confianza (TEST QA 4)', () => {
  const result = reconcilePrice([
    { precioUnitario: 250, confidence: 40 },
    { precioUnitario: 300, confidence: 85 }
  ]);
  assert.equal(result.rule, RECONCILIATION_RULE.MAYOR_CONFIANZA);
  assert.equal(result.precioUnitario, 300);
  assert.equal(result.confidence, 85);
});

test('reconcilePrice: empate en la confianza mas alta -> mediana de los empatados', () => {
  const result = reconcilePrice([
    { precioUnitario: 100, confidence: 70 },
    { precioUnitario: 200, confidence: 70 },
    { precioUnitario: 900, confidence: 20 } // no participa: no tiene la confianza maxima
  ]);
  assert.equal(result.rule, RECONCILIATION_RULE.EMPATE_MEDIANA);
  assert.equal(result.precioUnitario, median([100, 200]));
  assert.deepEqual(result.empatados.sort((a, b) => a - b), [100, 200]);
});

test('median: par e impar', () => {
  assert.equal(median([1, 3]), 2);
  assert.equal(median([1, 2, 9]), 2);
});

test('assertSingleTenantScope rechaza APUs de organizaciones distintas (TEST QA 14)', () => {
  assert.throws(() => assertSingleTenantScope([
    { id: 'a', organizationId: 'org-1' },
    { id: 'b', organizationId: 'org-2' }
  ]), /organizaciones distintas/);
});

test('assertSingleTenantScope acepta la misma organizacion (o todos individuales/null)', () => {
  assert.doesNotThrow(() => assertSingleTenantScope([
    { id: 'a', organizationId: 'org-1' },
    { id: 'b', organizationId: 'org-1' }
  ]));
  assert.doesNotThrow(() => assertSingleTenantScope([{ id: 'a', organizationId: null }, { id: 'b', organizationId: null }]));
});

test('buildExplosionSnapshot produce forma serializable con hash estable y determinista', async () => {
  const args = { projectId: 'P1', organizationId: 'O1', sourceApuIds: ['b', 'a'], totals: { x: 1 }, rows: { materials: [] } };
  const snap1 = await buildExplosionSnapshot(args);
  const snap2 = await buildExplosionSnapshot(args);
  assert.equal(snap1.reconciliationHash, snap2.reconciliationHash);
  assert.deepEqual(snap1.sourceApuIds, ['a', 'b']); // orden normalizado, no depende del orden de entrada
  assert.ok(snap1.generatedAt);
  assert.equal(snap1.engineVersion, 'explosion-v1');
});
