/* Motor compartido de "Explosiones" (Fase A -- materiales, mano de obra,
   maquinaria/equipo consolidados a traves de uno o varios APU/proyecto).
   Modulo puro (sin React/Firebase): src/domain/materialExplosion.js,
   laborExplosion.js y machineryExplosion.js reusan SOLO estas funciones para
   que las 3 explosiones agrupen/reconcilien/versionen de forma identica --
   ninguna reimplementa su propia regla de agrupacion o de hash.

   Fuente de verdad de cada APU: `apus/{id}.snapshot`, que _route-apus.mjs
   SIEMPRE persiste ya pasado por finalizeProfessionalAPU (ver
   apuVersioning.js#createApuVersion) -- es decir, esquema v2 (renglones-
   objeto: clave/descripcion/unidad/consumo/desperdicioPct/precioUnitario/
   fuente/priceRecord), nunca el v1 de arrays posicionales. Este motor asume
   ese esquema; no migra nada, no acepta v1. */

import { computeSnapshotHash } from './snapshotHash.js';

export const EXPLOSION_ENGINE_VERSION = 'explosion-v1';

/* ---------- Identidad de agrupacion ---------- */

/* Normaliza texto para comparar descripciones de material/mano de obra sin
   que acentos/mayusculas/espacios dobles generen grupos falsos-distintos.
   Mismo espiritu (NFD + strip de diacriticos) que ya usan
   materialOrigin.js#normalize y apuWorkspace.js#duplicateGroupKey -- no se
   importa de ahi porque esos modulos resuelven un problema distinto
   (coincidencia de texto dentro de un concepto / dedupe de un solo lote) y
   acoplarlos aqui haria que un cambio en su logica alterara, sin querer, el
   agrupamiento de la Explosion. */
export function foldDescription(value){
  return String(value ?? '')
    .toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/* Normaliza una unidad SOLO para comparar si dos renglones son "la misma
   unidad" (m2/M2/m² deben coincidir; "bulto" y "kg" NUNCA deben coincidir,
   ver regla explicita del usuario: "Cemento CPC 30R / bulto" y "/ kg" no se
   fusionan sin conversion explicita -- esta funcion no convierte nada, solo
   normaliza cosmeticamente). Mismo criterio que
   src/domain/unitAuthority.js#normalizeUnitForCompare (privada ahi, no
   exportada) -- se replica aqui deliberadamente en vez de exportarla desde
   unitAuthority.js para no acoplar la resolucion de inputs de usuario/IA de
   ese modulo con el agrupamiento de la Explosion. */
export function normalizeUnitForGrouping(value){
  return String(value ?? '').trim().toLowerCase()
    .replace(/[²]/g, '2').replace(/[³]/g, '3')
    .replace(/\s+/g, '');
}

/* Una `clave` es "confiable" (identidad estable entre APUs) solo si NO es el
   placeholder autogenerado que apuSchema.js asigna cuando el renglon no vino
   de un catalogo real (MAT-001, MO-002, EQ-003, CON-004, SEG-005 -- ver
   migrateMaterialRow/migrateLaborRow/migrateEquipmentRow y
   normalizeAIApuToV2 en src/domain/apuSchema.js). Ese placeholder se genera
   POR INDICE dentro de cada APU: dos renglones de "Cemento" en dos APUs
   distintos pueden terminar los dos con clave "MAT-001" sin ser el mismo
   material -- agrupar por eso fusionaria materiales no relacionados. Si la
   clave NO coincide con el patron, se asume que vino de un catalogo real
   (Biblioteca, importacion, captura manual de codigo de proveedor) y es
   segura para agrupar. */
const AUTOGENERATED_CLAVE_PATTERNS = {
  materials: /^MAT-\d+$/i,
  consumables: /^CON-\d+$/i,
  labor: /^MO-\d+$/i,
  equipment: /^EQ-\d+$/i,
  seguridad: /^SEG-\d+$/i
};
export function isAutogeneratedClave(clave, kind){
  const pattern = AUTOGENERATED_CLAVE_PATTERNS[kind];
  const value = String(clave ?? '').trim();
  if(!value) return true;
  // Sin patron conocido para este `kind` (ej. herramientaMenor.detalle, que
  // no tiene un prefijo autogenerado documentado en apuSchema.js): se asume
  // NO confiable por defecto -- agrupar de mas por descripcion nunca fusiona
  // datos distintos, agrupar de menos por una clave falsa-estable si podria.
  return pattern ? pattern.test(value) : true;
}

/* Clave de agrupacion de un renglon: `clave:<clave>` cuando es confiable,
   `desc:<descripcion normalizada>` en otro caso -- SIEMPRE con la unidad
   normalizada como sufijo (incluso cuando se agrupa por clave real: si por
   error de captura la MISMA clave trae dos unidades distintas entre APUs,
   esto las separa en vez de fusionarlas silenciosamente; nunca reduce
   grupos, solo puede aumentarlos frente a un dato inconsistente). */
export function groupKeyFor(row, kind){
  const clave = String(row?.clave ?? '').trim();
  const reliable = clave && !isAutogeneratedClave(clave, kind);
  const identity = reliable ? `clave:${clave.toLowerCase()}` : `desc:${foldDescription(row?.descripcion)}`;
  return `${identity}|unidad:${normalizeUnitForGrouping(row?.unidad)}`;
}

/* ---------- Reconciliacion de precios divergentes ---------- */

export const RECONCILIATION_RULE = Object.freeze({
  UNICO: 'UNICO', // todos los origenes coinciden en el mismo precio
  MAYOR_CONFIANZA: 'MAYOR_CONFIANZA', // un origen tiene priceRecord.confidence estrictamente mayor
  EMPATE_MEDIANA: 'EMPATE_MEDIANA' // empate en la confianza mas alta -> mediana de los precios empatados
});

export function median(values){
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  if(sorted.length % 2 === 0) return (sorted[mid - 1] + sorted[mid]) / 2;
  return sorted[mid];
}

/* reconcilePrice: decide el "precio consolidado" de un grupo cuando sus
   origenes no coinciden en precio unitario. NUNCA promedia en silencio ni
   toma "el primero" -- la regla aplicada siempre queda declarada en el
   resultado (reconciliationRule) junto con el detalle completo de origenes
   (ver buildOriginRows en cada motor especifico), para que la decision sea
   auditable en la UI/Excel/PDF ("no quiero una regla silenciosa").

   candidates: [{ precioUnitario:number, confidence:number (0-100) }] -- ya
   filtrados a los que SI aportan cantidad > 0 a este grupo. */
export function reconcilePrice(candidates){
  const valid = (candidates || []).filter(c => Number.isFinite(c?.precioUnitario));
  if(!valid.length) return { precioUnitario: 0, confidence: 0, rule: RECONCILIATION_RULE.UNICO, empatados: [] };
  const maxConfidence = Math.max(...valid.map(c => Number(c.confidence) || 0));
  const distinctPrices = [...new Set(valid.map(c => round2(c.precioUnitario)))];
  if(distinctPrices.length === 1){
    return { precioUnitario: distinctPrices[0], confidence: maxConfidence, rule: RECONCILIATION_RULE.UNICO, empatados: [] };
  }
  const winners = valid.filter(c => (Number(c.confidence) || 0) === maxConfidence);
  const winnerDistinctPrices = [...new Set(winners.map(c => round2(c.precioUnitario)))];
  if(winnerDistinctPrices.length === 1){
    return { precioUnitario: winnerDistinctPrices[0], confidence: maxConfidence, rule: RECONCILIATION_RULE.MAYOR_CONFIANZA, empatados: [] };
  }
  return { precioUnitario: round2(median(winnerDistinctPrices)), confidence: maxConfidence, rule: RECONCILIATION_RULE.EMPATE_MEDIANA, empatados: winnerDistinctPrices };
}

export function round2(value){
  return Math.round((Number(value) || 0) * 100) / 100;
}

/* ---------- Aislamiento multi-tenant (defensa en profundidad) ---------- */

/* Los APUs que alimentan una Explosion SIEMPRE deben venir de
   loadProjectApus()/GET /api/apus?projectId= (ver apuProjectDossierData.js),
   que ya filtra server-side por organizationId/ownerUid derivado del token
   (nunca del cliente, ver _orgGuard.mjs#loadOrgContext). Esta funcion es una
   segunda barrera, no la primera: si por cualquier razon (bug de llamador,
   union manual de dos listas) el motor recibe documentos de mas de una
   organizacion/proyecto, se rechaza el calculo COMPLETO en vez de mezclar
   precios/cantidades de organizaciones distintas en silencio. */
export function assertSingleTenantScope(apuDocs){
  const orgIds = new Set((apuDocs || []).map(d => d?.organizationId ?? null));
  if(orgIds.size > 1){
    throw new Error(`No se puede consolidar: los APUs pertenecen a ${orgIds.size} organizaciones distintas (${[...orgIds].join(', ')}). Una Explosion nunca mezcla datos entre organizaciones.`);
  }
}

/* ---------- Snapshot serializable/versionable (Fase A, sin coleccion nueva) ---------- */

/* Forma unica devuelta por buildMaterialExplosion/buildLaborExplosion/
   buildMachineryExplosion + el orquestador de UI que las combina. Se calcula
   100% en memoria a partir de los APUs ya cargados -- no persiste nada
   todavia (regla explicita del usuario: "no crees una coleccion nueva si no
   es necesaria"). El shape ya queda listo para guardarse tal cual como
   documento `explosionSnapshots/{id}` en una subfase futura sin tener que
   tocar el motor: bastaria con un endpoint que reciba este mismo objeto. */
export async function buildExplosionSnapshot({ projectId = null, organizationId = null, sourceApuIds = [], totals = {}, rows = {} }){
  const base = { projectId, organizationId, sourceApuIds: [...sourceApuIds].sort(), engineVersion: EXPLOSION_ENGINE_VERSION, totals, rows };
  const reconciliationHash = await computeSnapshotHash(base);
  return { ...base, generatedAt: new Date().toISOString(), reconciliationHash };
}
